

# Configuração do Banco de Dados H2 em memória para testes manuais
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cria as tabelas automaticamente baseado nas nossas classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o console do banco H2 no navegador (opcional, mas muito útil)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console